<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="master.css">
        <meta charset="utf-8">
        <title>V2</title>
    </head>
    <body>
        <?php
        function color(){
            $a = 0;
            while ($a <= 100) {
                $code = 'rgb(' . mt_rand(0 , 255) . ',' . mt_rand(0 , 255) . ',' . mt_rand(0 , 255) . ')';
                echo '<div class="code" style ="background-color:'.$code.';"><div class="texte">'.$code.'</div></div>';
                $a = $a + 1 ;
            }
        }
        color();
        ?>
    </body>
</html>
